### PR TITLE
add website url to readme

### PR DESCRIPTION
**Pull request by boltalex389-2nd-account**

### CODE REVIEW

**Comment by boltalex389-2nd-account** [comment]
This is a minor commit, for your info

**Comment by boltalex389-2nd-account** [comment]
Thanks.

**Comment by boltalex389-2nd-account** [comment]
Oh, and thanks for kicking me too. I didn't do anything wrong. I was trying to help

**Comment by boltalex389-2nd-account** [comment]
@ririxidev

**Comment by abbie140703** [comment]
Who is this?

**Comment by ririxidev** [comment]
I shouldn't explain it there but sure I will do it. ToS Violation aka Self-bot using Watching status that is prohibited for users to use. This is considered for bots only. We can only use Playing status and Listening to on Spotify. Thanks.

**Comment by boltalex389-2nd-account** [comment]
I AM NOT A BOT

**Pull request closed without merging**
