### PR TITLE
Add gentoo to the installation section

### PR DESCRIPTION
**Pull request by apriluwu**

### CODE REVIEW

**Comment by doomlerd** [comment]
Would be better if you add the required files in the main PR, so that they can be maintained in the future and not count as 3rd party.

**Comment by apriluwu** [comment]
> required files
?

**Comment by doomlerd** [comment]
> ?
https://github.com/apriluwu/gentoo-overlay

**Comment by apriluwu** [comment]
What required files though? In my recent commit there is no direct link to files due to my overlay being added to [gentoo/api-gentoo-org](https://github.com/gentoo/api-gentoo-org)

**Comment by doomlerd** [comment]
Yeah but it still says your name instead of PreMiD's, hence it is not really official but simply third party.

**Comment by apriluwu** [comment]
I mean.. that's kinda how overlays work? I'm just the maintainer of the package. I can't really just rename it to premid just for one package

**Comment by doomlerd** [comment]
According to https://devmanual.gentoo.org/ebuild-writing/misc-files/metadata, the type can be a project instead of a person, yours says otherwise so I'm sure there's a way.

**Comment by apriluwu** [comment]
It's one package though, which I will be adding more packages that are not related to premid when I get around to it. This isn't an overlay full of premid only packages

**Comment by doomlerd** [comment]
Well it definitely would be better to have it named after the org's name, many paranoid users asked about whether [doomlerd/PreMiD-Linux](https://github.com/doomlerd/PreMiD-Linux) was safe or not considering it was technically third party so it wouldn't be different in this case either. I'm completely fine with you being the maintainer of it that package though, it just needs to be in a more official way,

**Comment by apriluwu** [comment]
I don't understand the case of the AUR then though? AUR is unstable and technically third party. Also build files can easily be checked, which I'm sure if you're using gentoo and know how to add an overlay they can do themselves.

If I absolutely MUST I can make a separate overlay for it which can be maintained on the PreMiD org, but I do not think it will be enough for it to be "officially" added to gentoo/api-gentoo-org and will result in adding the overlay through a sort of hacky method.

**Comment by doomlerd** [comment]
> I don't understand the case of the AUR then though? AUR is unstable and technically third party. Also build files can easily be checked, which I'm sure if you're using gentoo and know how to add an overlay they can do themselves.

The AUR package is maintained by me ( premid-git wasn't which caused it to never be added here as a method *yet* ), and even then my name isn't involved in the process of installing the package and it is pretty much stable.

> If I absolutely MUST I can make a separate overlay for it which can be maintained on the PreMiD org, but I do not think it will be enough for it to be "officially" added to gentoo/api-gentoo-org and will result in adding the overlay through a sort of hacky method.

I'd appreciate it if you could, it's not really a matter of who's the maintainer as long as the installation commands only include the package name, that way it looks more "official" ( if there's a way to do it now there'd be no need to make a separate overlay ).

**Comment by apriluwu** [comment]
I think making another overlay would be the better option in that case, I'd like to use my overlay for other packages as well in the future. But again I do not think it's enough to get it added to the overlay remote list, which will mean it will have to be a bit hacky (directly adding the overlay through a link rather than fetching from the remote list) if you're ok with that.

**Comment by doomlerd** [comment]
Are you sure it won't be accepted?

**Comment by apriluwu** [comment]
I can't say for certain but a project overlay with only one package seems unlikely

**Comment by doomlerd** [comment]
Well then, I'll merge this for now.

**Pull request merged**
